config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  resources :code_frames, path: :frames do
    resources :code_snippets, only: [:create]
  end

  resources :code_snippets, only: [:show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/code_frame.rb
class CodeFrame < ApplicationRecord
  has_many :code_snippets

  attribute :title
  attribute :description

  enum status: [ :draft, :published ]
end

app/models/code_snippet.rb
class CodeSnippet < ApplicationRecord
  LANGUAGES = %w(ruby html css javascript markdown)

  belongs_to :code_frame

  attribute :file_name
  attribute :content

  validates :language, inclusion: { in: LANGUAGES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/code_frames_controller.rb
class CodeFramesController < ApplicationController
  def index
    @code_frames = CodeFrame.all
  end

  def new
    @code_frame = CodeFrame.find_or_create_by(status: "draft")
    if @code_frame.code_snippets.empty?
      @code_frame.code_snippets.build(language: "html", content: "")
      @code_frame.code_snippets.build(language: "css", content: "")
      @code_frame.code_snippets.build(language: "javascript", content: "")
      @code_frame.code_snippets.map(&:save)
    end
  end

  def show
    @code_frame = CodeFrame.find(params[:id])
  end

  def update
    @code_frame = CodeFrame.update(params[:id], code_frame_params.merge(status: "published"))

    code_snippets_json = JSON.parse(params[:code_snippets])
    code_snippets_json.each do |code_snippet_json|
      CodeSnippet.update(code_snippet_json["id"], code_snippet_json)
    end

    respond_to do |format|
      format.json do
        if @code_frame.save
          render json: {
            redirected: true,
            url: code_frame_url(@code_frame)
          }
        else
          render json: @code_frame.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def code_frame_params
    params.require(:code_frame).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/code_frames/_control_panel.html.erb
<%= form_for code_frame, data: { action: "submit->code-editor#saveFrame" } do |form| %>
  <div class="mb-6">
    <%= form.label :title, "Frame Title", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-slate-500 focus:border-slate-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-slate-500 dark:focus:border-slate-500" %>
  </div>
  <div class="mb-6">
    <%= form.label :description, "Description", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_area :description, class: "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-slate-500 focus:border-slate-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-slate-500 dark:focus:border-slate-500" %>
  </div>
  <div class="flex justify-between items-center">
    <%= form.submit "Save", class: "text-white bg-slate-700 hover:bg-slate-800 focus:ring-4 focus:outline-none focus:ring-slate-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-slate-600 dark:hover:bg-slate-700 dark:focus:ring-slate-800" %>

    <div data-action="click->code-editor#closeModal" class="text-gray-400 cursor-pointer underline decoration-dotted underline-offset-4">esc</div>
  </div>

<% end %>

app/views/code_frames/_project.html.erb
<div class="lg:h-full" data-controller="code-editor" id="code-editor" data-code-editor-inactive-klass-value="text-slate-400 hover:text-slate-800" data-code-editor-active-klass-value="border-b-4 border-slate-800 text-slate-800 hover:text-slate-400">
  <div class="h-full w-full pt-2 lg:columns-2 gap-1" >
    <div class="flex flex-col lg:h-full h-1/2">
      <div class="flex justify-between">
        <div class="px-5">
          <button class="hover:bg-slate-200 text-slate-800 hover:text-slate-400 text-xs py-1 px-4 mx-1 rounded-t border-b-4 border-slate-800" data-code-editor-target="languageToggle" data-language="html">
            <i class="fa-brands fa-html5"></i> &nbsp;
            html
          </button>
          <button class="hover:bg-slate-200 text-slate-400 hover:text-slate-800 text-xs py-1 px-4 mx-1 rounded-t" data-code-editor-target="languageToggle" data-language="css">
            <i class="fa-brands fa-css3-alt"></i> &nbsp;
            css
          </button>
          <button class="hover:bg-slate-200 text-slate-400 hover:text-slate-800 text-xs py-1 px-4 mx-1 rounded-t" data-code-editor-target="languageToggle" data-language="javascript">
            <i class="fa-brands fa-square-js"></i> &nbsp;
            js
          </button>
        </div>
      </div>
      <% code_frame.code_snippets.each_with_index do |code_snippet, index| %>
        <div class="flex-1 <%= index.zero? ? "" : "hidden" %>" data-code-editor-target="editor" data-snippet-id="<%= code_snippet.id %>" data-language="<%= code_snippet.language %>">
          <textarea class="hidden">
              <%= code_snippet.content %>
          </textarea>
        </div>
      <% end %>
    </div>

    <div class="flex flex-col lg:h-full h-1/2">
      <div class="">
        <div class="">
          <button class="text-slate-400 text-xs py-1 px-4 mx-1 rounded-t border-b-4 border-slate-400 flex items-center">
            Hot Reload &nbsp;
            <div class="p-1 flex items-center">
              <svg height="0.6rem" fill="rgb(148 163 184)" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 80 80" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M64,48L64,48h-8V32h8c8.836,0,16-7.164,16-16S72.836,0,64,0c-8.837,0-16,7.164-16,16v8H32v-8c0-8.836-7.164-16-16-16 S0,7.164,0,16s7.164,16,16,16h8v16h-8l0,0l0,0C7.164,48,0,55.164,0,64s7.164,16,16,16c8.837,0,16-7.164,16-16l0,0v-8h16v7.98 c0,0.008-0.001,0.014-0.001,0.02c0,8.836,7.164,16,16,16s16-7.164,16-16S72.836,48.002,64,48z M64,8c4.418,0,8,3.582,8,8 s-3.582,8-8,8h-8v-8C56,11.582,59.582,8,64,8z M8,16c0-4.418,3.582-8,8-8s8,3.582,8,8v8h-8C11.582,24,8,20.417,8,16z M16,72 c-4.418,0-8-3.582-8-8s3.582-8,8-8l0,0h8v8C24,68.418,20.418,72,16,72z M32,48V32h16v16H32z M64,72c-4.418,0-8-3.582-8-8l0,0v-8 h7.999c4.418,0,8,3.582,8,8S68.418,72,64,72z"></path> </g> </g></svg>
              <span class="pl-[2px]">
                S
              </span>
            </div>
          </button>
        </div>
      </div>
      <iframe style="width: 100%; height: 100%; background: white;">
      </iframe>
    </div>
  </div>
  <div data-code-editor-target="modal"
       class="hidden w-full h-full fixed z-50 top-0 left-0 bg-black bg-opacity-80"
  >
    <div
      class="
    z-[1100]
    bg-white
    max-h-[75%]
    w-6/12
    rounded-md
    p-8
    absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
    >
      <%= render "control_panel", code_frame: %>
    </div>
  </div>
</div>

app/views/code_frames/index.html.erb
<% content_for :navbar do %>
  <div data-controller="code-editor-panel">
    <%= link_to "New Frame", new_code_frame_path,
      class: "flex text-white text-xs py-2 px-5 mx-1 rounded-md bg-slate-800 items-center"
    %>
  </div>
<% end %>

<div class="lg:h-full" data-controller="code-editor" id="code-editor" data-code-editor-inactive-klass-value="text-slate-400 hover:text-slate-800" data-code-editor-active-klass-value="border-b-4 border-slate-800 text-slate-800 hover:text-slate-400">

</div>

app/views/code_frames/new.html.erb
<% content_for :navbar do %>
  <div data-controller="code-editor-panel">
    <button
      data-action="click->code-editor-panel#save"
      class="
      flex
      text-white
      text-xs
      py-2
      px-5
      mx-1
      rounded-md
      bg-slate-800
      items-center
">
      <span>Save Frame</span> &nbsp;
      <span class="p-1 flex items-center">
        <svg height="0.6rem" fill="#ffffff" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 80 80" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M64,48L64,48h-8V32h8c8.836,0,16-7.164,16-16S72.836,0,64,0c-8.837,0-16,7.164-16,16v8H32v-8c0-8.836-7.164-16-16-16 S0,7.164,0,16s7.164,16,16,16h8v16h-8l0,0l0,0C7.164,48,0,55.164,0,64s7.164,16,16,16c8.837,0,16-7.164,16-16l0,0v-8h16v7.98 c0,0.008-0.001,0.014-0.001,0.02c0,8.836,7.164,16,16,16s16-7.164,16-16S72.836,48.002,64,48z M64,8c4.418,0,8,3.582,8,8 s-3.582,8-8,8h-8v-8C56,11.582,59.582,8,64,8z M8,16c0-4.418,3.582-8,8-8s8,3.582,8,8v8h-8C11.582,24,8,20.417,8,16z M16,72 c-4.418,0-8-3.582-8-8s3.582-8,8-8l0,0h8v8C24,68.418,20.418,72,16,72z M32,48V32h16v16H32z M64,72c-4.418,0-8-3.582-8-8l0,0v-8 h7.999c4.418,0,8,3.582,8,8S68.418,72,64,72z"></path> </g> </g></svg>
        <span class="pl-[2px]">
          <svg height="0.65rem" fill="#ffffff" viewBox="0 0 56 56" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M 19.2811 49.5156 C 20.5233 49.5156 21.3436 48.6719 21.3436 47.4531 C 21.3436 46.8438 21.1561 46.3984 20.7811 46.0234 L 14.0311 39.4375 L 9.5780 35.6406 L 15.0858 35.8750 L 44.9920 35.8750 C 50.4529 35.8750 52.7267 33.3672 52.7267 28.0703 L 52.7267 14.2188 C 52.7267 8.7578 50.4529 6.4844 44.9920 6.4844 L 31.8671 6.4844 C 30.5780 6.4844 29.7342 7.4219 29.7342 8.5703 C 29.7342 9.7188 30.5780 10.6562 31.8671 10.6562 L 44.9920 10.6562 C 47.4764 10.6562 48.5545 11.7344 48.5545 14.2188 L 48.5545 28.0703 C 48.5545 30.6250 47.4764 31.7031 44.9920 31.7031 L 15.0858 31.7031 L 9.5780 31.9375 L 14.0311 28.1406 L 20.7811 21.5547 C 21.1561 21.1797 21.3436 20.7109 21.3436 20.1016 C 21.3436 18.9062 20.5233 18.0391 19.2811 18.0391 C 18.7655 18.0391 18.1561 18.2969 17.7577 18.6953 L 3.9764 32.2188 C 3.5077 32.6640 3.2733 33.2031 3.2733 33.7891 C 3.2733 34.3516 3.5077 34.9140 3.9764 35.3594 L 17.7577 48.8828 C 18.1561 49.2813 18.7655 49.5156 19.2811 49.5156 Z"></path></g></svg>
        </span>
      </span>
    </button>
  </div>
<% end %>

<%= render "project", code_frame: @code_frame %>

app/views/code_frames/show.html.erb
<% content_for :navbar do %>
  <div data-controller="code-editor-panel">
    <button
      data-action="click->code-editor-panel#save"
      class="
      flex
      text-white
      text-xs
      py-2
      px-5
      mx-1
      rounded-md
      bg-slate-800
      items-center
">
      <span>Update Frame</span> &nbsp;
      <span class="p-1 flex items-center">
        <svg height="0.6rem" fill="#ffffff" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 80 80" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M64,48L64,48h-8V32h8c8.836,0,16-7.164,16-16S72.836,0,64,0c-8.837,0-16,7.164-16,16v8H32v-8c0-8.836-7.164-16-16-16 S0,7.164,0,16s7.164,16,16,16h8v16h-8l0,0l0,0C7.164,48,0,55.164,0,64s7.164,16,16,16c8.837,0,16-7.164,16-16l0,0v-8h16v7.98 c0,0.008-0.001,0.014-0.001,0.02c0,8.836,7.164,16,16,16s16-7.164,16-16S72.836,48.002,64,48z M64,8c4.418,0,8,3.582,8,8 s-3.582,8-8,8h-8v-8C56,11.582,59.582,8,64,8z M8,16c0-4.418,3.582-8,8-8s8,3.582,8,8v8h-8C11.582,24,8,20.417,8,16z M16,72 c-4.418,0-8-3.582-8-8s3.582-8,8-8l0,0h8v8C24,68.418,20.418,72,16,72z M32,48V32h16v16H32z M64,72c-4.418,0-8-3.582-8-8l0,0v-8 h7.999c4.418,0,8,3.582,8,8S68.418,72,64,72z"></path> </g> </g></svg>
        <span class="pl-[2px]">
          <svg height="0.65rem" fill="#ffffff" viewBox="0 0 56 56" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M 19.2811 49.5156 C 20.5233 49.5156 21.3436 48.6719 21.3436 47.4531 C 21.3436 46.8438 21.1561 46.3984 20.7811 46.0234 L 14.0311 39.4375 L 9.5780 35.6406 L 15.0858 35.8750 L 44.9920 35.8750 C 50.4529 35.8750 52.7267 33.3672 52.7267 28.0703 L 52.7267 14.2188 C 52.7267 8.7578 50.4529 6.4844 44.9920 6.4844 L 31.8671 6.4844 C 30.5780 6.4844 29.7342 7.4219 29.7342 8.5703 C 29.7342 9.7188 30.5780 10.6562 31.8671 10.6562 L 44.9920 10.6562 C 47.4764 10.6562 48.5545 11.7344 48.5545 14.2188 L 48.5545 28.0703 C 48.5545 30.6250 47.4764 31.7031 44.9920 31.7031 L 15.0858 31.7031 L 9.5780 31.9375 L 14.0311 28.1406 L 20.7811 21.5547 C 21.1561 21.1797 21.3436 20.7109 21.3436 20.1016 C 21.3436 18.9062 20.5233 18.0391 19.2811 18.0391 C 18.7655 18.0391 18.1561 18.2969 17.7577 18.6953 L 3.9764 32.2188 C 3.5077 32.6640 3.2733 33.2031 3.2733 33.7891 C 3.2733 34.3516 3.5077 34.9140 3.9764 35.3594 L 17.7577 48.8828 C 18.1561 49.2813 18.7655 49.5156 19.2811 49.5156 Z"></path></g></svg>
        </span>
      </span>
    </button>
  </div>
<% end %>

<%= render "project", code_frame: @code_frame %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>copium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <main class="h-0 min-h-screen pt-12">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<div class="bg-white">
    <div class="mx-auto max-w-2xl py-20">
<!--      <div class="hidden sm:mb-8 sm:flex sm:justify-center">-->
<!--        <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">-->
<!--          Announcing our next round of funding. <a href="#" class="font-semibold text-indigo-600"><span class="absolute inset-0" aria-hidden="true"></span>Read more <span aria-hidden="true">&rarr;</span></a>-->
<!--        </div>-->
<!--      </div>-->
      <script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script>
      <div style="height:300px" align="center">
        <dotlottie-player src="https://lottie.host/6edadd2a-7fa4-40b7-bfc7-7dc2ba2eddad/QsZREXw410.json" background="transparent" speed="1" style="width: 300px; height: 300px;" loop autoplay></dotlottie-player>
      </div>
      <div class="text-center">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">snippets of wisdom</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">
          a playground for your code snippets
        </p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
          <a id="get-started" href="/frames/new" class="rounded-md bg-slate-800 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-600">
            <div class="p-1 flex items-center">
              Get started &nbsp;
              <svg height="0.6rem" fill="rgb(148 163 184)" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 80 80" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M64,48L64,48h-8V32h8c8.836,0,16-7.164,16-16S72.836,0,64,0c-8.837,0-16,7.164-16,16v8H32v-8c0-8.836-7.164-16-16-16 S0,7.164,0,16s7.164,16,16,16h8v16h-8l0,0l0,0C7.164,48,0,55.164,0,64s7.164,16,16,16c8.837,0,16-7.164,16-16l0,0v-8h16v7.98 c0,0.008-0.001,0.014-0.001,0.02c0,8.836,7.164,16,16,16s16-7.164,16-16S72.836,48.002,64,48z M64,8c4.418,0,8,3.582,8,8 s-3.582,8-8,8h-8v-8C56,11.582,59.582,8,64,8z M8,16c0-4.418,3.582-8,8-8s8,3.582,8,8v8h-8C11.582,24,8,20.417,8,16z M16,72 c-4.418,0-8-3.582-8-8s3.582-8,8-8l0,0h8v8C24,68.418,20.418,72,16,72z M32,48V32h16v16H32z M64,72c-4.418,0-8-3.582-8-8l0,0v-8 h7.999c4.418,0,8,3.582,8,8S68.418,72,64,72z"></path> </g> </g></svg>
              <span class="pl-[2px]">
                <svg height="0.7rem" fill="rgb(148 163 184)" viewBox="0 0 56 56" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M 19.2811 49.5156 C 20.5233 49.5156 21.3436 48.6719 21.3436 47.4531 C 21.3436 46.8438 21.1561 46.3984 20.7811 46.0234 L 14.0311 39.4375 L 9.5780 35.6406 L 15.0858 35.8750 L 44.9920 35.8750 C 50.4529 35.8750 52.7267 33.3672 52.7267 28.0703 L 52.7267 14.2188 C 52.7267 8.7578 50.4529 6.4844 44.9920 6.4844 L 31.8671 6.4844 C 30.5780 6.4844 29.7342 7.4219 29.7342 8.5703 C 29.7342 9.7188 30.5780 10.6562 31.8671 10.6562 L 44.9920 10.6562 C 47.4764 10.6562 48.5545 11.7344 48.5545 14.2188 L 48.5545 28.0703 C 48.5545 30.6250 47.4764 31.7031 44.9920 31.7031 L 15.0858 31.7031 L 9.5780 31.9375 L 14.0311 28.1406 L 20.7811 21.5547 C 21.1561 21.1797 21.3436 20.7109 21.3436 20.1016 C 21.3436 18.9062 20.5233 18.0391 19.2811 18.0391 C 18.7655 18.0391 18.1561 18.2969 17.7577 18.6953 L 3.9764 32.2188 C 3.5077 32.6640 3.2733 33.2031 3.2733 33.7891 C 3.2733 34.3516 3.5077 34.9140 3.9764 35.3594 L 17.7577 48.8828 C 18.1561 49.2813 18.7655 49.5156 19.2811 49.5156 Z"></path></g></svg>
              </span>
            </div>
          </a>
          <a target="_blank" href="https://github.com/zonghangoh/copium" class="text-sm font-semibold leading-6 text-gray-900">Source Code <span aria-hidden="true">→</span></a>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
  document.addEventListener("keydown", function(event){
    if (event.metaKey && event.key === "Enter") {
        event.preventDefault()
        window.location.href = "/frames/new"
    }
  })
</script>

app/views/shared/_navbar.html.erb
<nav class="flex justify-between items-center h-12 fixed w-full px-4 border-b-2 border-slate-100">
  <div class="flex">
    <%= link_to root_path do %>
      <img class="h-10" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxGbQRg7fo_DLbFyuf9dU6K1QDjFo-Ub7s3A&usqp=CAU">
    <% end %>
  </div>
  <div>
    <%= yield :navbar %>
  </div>
</nav>